name: Build LLDB iOS Static Library

on:
  push:
    branches: [ main, master, develop, '*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        submodules: 'recursive'
    
    - name: Install CMake and LLVM
      run: |
        brew install cmake ninja llvm
        echo "LLVM_PATH=$(brew --prefix llvm)" >> $GITHUB_ENV
        echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Download iOS toolchain
      run: |
        curl -L https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake -o ios.toolchain.cmake

    - name: Build for iOS Device (arm64)
      run: |
        # First build LLVM with required components
        mkdir build-llvm
        cd build-llvm
        cmake ../llvm \
          -G Ninja \
          -C ../lldb/cmake/caches/Apple-lldb-base.cmake \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_TARGETS_TO_BUILD="AArch64" \
          -DLLVM_BUILD_TOOLS=ON \
          -DLLVM_INCLUDE_TOOLS=ON \
          -DLLVM_TOOL_CLANG_BUILD=ON \
          -DLLVM_DISTRIBUTION_COMPONENTS="clang;clang-resource-headers;clang-format;clang-tidy;clang-apply-replacements;clang-headers;libclang;libclang-headers"
        ninja distribution
        cd ..

        # Then build LLDB for iOS
        mkdir build-ios-device
        cd build-ios-device
        cmake ../lldb \
          -G Ninja \
          -C ../lldb/cmake/caches/Apple-lldb-base.cmake \
          -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake \
          -DPLATFORM=OS64 \
          -DARCHS="arm64" \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_DIR=../build-llvm/lib/cmake/llvm \
          -DCLANG_DIR=../build-llvm/lib/cmake/clang \
          -DLLDB_INCLUDE_TESTS=OFF \
          -DLLDB_USE_SYSTEM_DEBUGSERVER=ON \
          -DLLDB_ENABLE_PYTHON=OFF \
          -DLLDB_ENABLE_LIBEDIT=OFF \
          -DLLDB_ENABLE_CURSES=OFF \
          -DLLDB_ENABLE_LZMA=OFF \
          -DLLDB_ENABLE_LUA=OFF \
          -DLLDB_ENABLE_LIBXML2=OFF \
          -DLLDB_BUILD_FRAMEWORK=OFF \
          -DENABLE_BITCODE=0 \
          -DENABLE_ARC=0 \
          -DENABLE_VISIBILITY=1 \
          -DDEPLOYMENT_TARGET=13.0 \
          -DLLVM_DEFAULT_TARGET_TRIPLE="arm64-apple-ios13.0"

        ninja liblldb

    - name: Package Library
      run: |
        mkdir -p universal/lib
        mkdir -p universal/include
        
        # Copy LLDB libraries
        find build-ios-device -name "liblldb*.a" -exec cp {} universal/lib/ \;
        
        # Copy headers
        cp -r lldb/include/* universal/include/
        
        # Create zip package
        cd universal
        zip -r ../lldb-ios.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lldb-ios
        path: lldb-ios.zip