name: Build LLVM iOS Static Library

on:
  push:
    branches: [ main, master, develop, '*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: llvm/llvm-project
        submodules: 'recursive'
    
    - name: Install CMake
      run: |
        brew install cmake ninja

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Download iOS toolchain
      run: |
        curl -L https://raw.githubusercontent.com/leetal/ios-cmake/master/ios.toolchain.cmake -o ios.toolchain.cmake

    - name: Build for iOS Device (arm64)
      run: |
        mkdir build-ios-device
        cd build-ios-device
        cmake .. \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=../ios.toolchain.cmake \
          -DPLATFORM=OS64 \
          -DENABLE_BITCODE=0 \
          -DENABLE_ARC=0 \
          -DENABLE_VISIBILITY=1 \
          -DARCHS="arm64" \
          -DCMAKE_BUILD_TYPE=Release \
          -DDEPLOYMENT_TARGET=13.0 \
          -DCMAKE_C_FLAGS="-arch arm64 -Wno-shorten-64-to-32" \
          -DCMAKE_CXX_FLAGS="-arch arm64 -Wno-shorten-64-to-32" \
          -DLLVM_TARGETS_TO_BUILD="AArch64;ARM" \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DLLVM_BUILD_TOOLS=OFF \
          -DLLVM_BUILD_UTILS=OFF \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_INCLUDE_EXAMPLES=OFF \
          -DLLVM_ENABLE_BACKTRACES=OFF \
          -DLLVM_ENABLE_TERMINFO=OFF \
          -DLLVM_ENABLE_ZLIB=OFF \
          -DLLVM_BUILD_STATIC=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_INSTALL_PREFIX=../install \
          -DLLVM_ENABLE_ASSERTIONS=OFF \
          -DLLVM_ENABLE_EH=OFF \
          -DLLVM_ENABLE_RTTI=OFF \
          -DLLVM_ENABLE_MODULES=OFF \
          -DLLVM_ENABLE_THREADS=ON \
          -DLLVM_OPTIMIZED_TABLEGEN=ON \
          -DLLVM_USE_INTEL_JITEVENTS=OFF \
          -DLLVM_USE_OPROFILE=OFF \
          -DLLVM_ENABLE_DIA_SDK=OFF \
          -DLLVM_ENABLE_FFI=OFF \
          -DLLVM_ENABLE_LIBEDIT=OFF \
          -DLLVM_ENABLE_LIBXML2=OFF \
          -DLLVM_ENABLE_OCAMLDOC=OFF \
          -DLLVM_ENABLE_LIBPFM=OFF \
          -DLLVM_ENABLE_BINDINGS=OFF

        ninja -j$(sysctl -n hw.ncpu)

    - name: Package Library
      run: |
        mkdir -p universal/lib
        
        # Copy LLVM libraries
        find . -name "*.a" -exec cp {} universal/lib/ \;
        
        # Copy headers
        mkdir -p universal/include
        cp -r ../llvm/include/* universal/include/ || true
        cp -r ../clang/include/* universal/include/ || true
        
        # Create zip package
        cd universal
        zip -r ../llvm-ios.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: llvm-ios
        path: llvm-ios.zip